# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  host: ec2-107-21-104-31.compute-1.amazonaws.com
  adapter: postgresql
  username: ccvnmscrnszwfl
  password: postgres://ccvnmscrnszwfl:20a3740401949f156f02489164d5a453194865e722af38f42c62d7fd4ce2d3bb@ec2-107-21-104-31.compute-1.amazonaws.com:5432/d611sc39pje9ci
  database: d611sc39pje9ci 
  pool: 5
  timeout: 5000



# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
adapter: postgresql
  timeout: 5000

test:
  <<: *default
  adapter: postgresql
  timeout: 5000

production:
  <<: *default
  adapter: postgresql
  timeout: 5000


